### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by sbrou** [sbrou/CashCash#5]
- [x] #4 
- [x] add a filter icon for the apply button in the filter tab
- [x] add a calendar down button for all the QDateEdit
- [x] open AddDialog to edit operation when double clicking on an operation in opsView
- [x] use QCheckBox for the state of chartsView ?
- [x] when removing a tag or category, ask the user if is sure by showing him the number of operations assigned to it and ask him if he wants to assign another tag or category to these operations or they will be assign "-NONE" by default
- [ ] have default values defined thorough all the code (today, today's month' today's year, etc...)
